### ISSUE TITLE
誤植: P119,120 6.1,

### ISSUE THREAD

**Issue by lightondust** [atarum/atarum.github.io#1]
６．１ですが、

# P119
１１９ページ「これをラグランジュ未定乗数法を用いて解くと」の下の数式

Ls = /lambda s + /mu 1

の最後の項が「/mu 1 Ls」となっていますが、「/mu 1」が正しいはずです

# P120
１２０ページ「ベクトルxは1とは直行であり」の下の式、最後の行

… + /frac{(n1-n2)^2}{n^2} n = ...

分母がn^2と２乗が抜けていました

@atarum

**Comment by atarum** [comment]
どうもありがとうございます。どちらもご指摘の通りです。atarum.github.ioの正誤表に追加致します。この本の第1版第3刷が来月に出るとの連絡があり、その修正には間に合わないかも知れません。もし第1版第4刷以降が出ることになりましたら、それには反映させようと思います。ありがとうございました。

**Comment by lightondust** [comment]
どういたしまして
